apache/entrypoint.sh
fpm-alpine/entrypoint.sh
fpm/entrypoint.sh

database connection checking with netcat is only possible when
using a TCP/IP connection, just launch the application when the
user chooses a unix socket

Add socket check before waiting for database connection

---

docker-compose.example.yml

I added a docker-compose.yml for people who don't want to clone the git repo before starting the container.

New docker-compose.yml which doesn't depend on the git repo

---

README.md
docker-compose.fpm-certbot.yml
examples/nginx-certbot.conf
nginx-certbot/Dockerfile
nginx-certbot/entrypoint.sh

The added configuration comes with a `certbot` container and configures Nginx to use a Letsencrypt certificate to provide https instead of http.

Added configuration which adds Nginx with Letsencrypt certificate

---

docker-compose.example.yml
docker-compose.fpm.alpine.yml
docker-compose.fpm.yml
docker-compose.pgsql.yml
docker-compose.yml

As hinted out in https://github.com/martialblog/docker-limesurvey/issues/32 it's possible (and more robust) to refer to the database host using its service name (i.e. lime-db or db).
I tested the Dockerfiles after this change.

Simplify database host values with compose

---

3.0/apache/Dockerfile
3.0/fpm-alpine/Dockerfile
3.0/fpm/Dockerfile
4.0/apache/Dockerfile
4.0/fpm-alpine/Dockerfile
4.0/fpm/Dockerfile

Since the PHP 7.2 support is going to end soon (30 Nov 2020) we'll update to PHP 7.4
PHP 7.4 is supported until 2022 and it is also recommended by the LimeSurvey Devs
> Minimum PHP 7.0 or later; however, we recommend PHP 7.4
> https://manual.limesurvey.org/Installation_-_LimeSurvey_CE#General
This makes #43 obsolete

Update Base Images to PHP 7.4

---

3.0/apache/entrypoint.sh
3.0/fpm-alpine/entrypoint.sh
3.0/fpm/entrypoint.sh

Limesurvey 3 won't support the encryption introduced in LS4, so the variables and the check for security.php isn't necessary in the entrypoint.sh files for LS3 Docker containers.

Remove unused references to encryption for LS3 entrypoints

---

docker-compose.example.yml
docker-compose.pgsql.yml

Hello @martialblog. Thanks for maintaining this repo :heart: 
I made some improvements to the docker-compose files so that the data saved in postgres are kept in volumes. Also updated from postgres 9.6 to 10 in `docker-compose.example.yml` to use the same version as in `docker-compose.pgsql.yml`

Use docker volumes for postgres database

---

.gitattributes
3.0/apache/entrypoint.sh
4.0/apache/entrypoint.sh
README.md

Some container orchestrators do not allow containers to use privileged ports (< 1024) by default, for example [OpenShift](https://docs.openshift.com/container-platform/4.7/openshift_images/create-images.html#images-create-guide-openshift_create-images).
Unfortunately, Apache uses 80 by default and changing the port requires modifying the Apache configuration files.
At my company we are using your wondeful image, but customized it to alter the Apache listen port (`Listen` and `VirtualHost` directives), and we are wondering, if we could bring that change back upstream.

Customize Apache listen port

---

3.0/apache/entrypoint.sh
4.0/apache/entrypoint.sh
5.0/apache/entrypoint.sh

Otherwise, if the replaced port number contains "80" (for example, "8080",
as is now the default), it is replaced over and over on each activation

Fix Apache LISTEN_PORT "sed" command to look for whole "Listen" command

---

3.0/apache/entrypoint.sh
3.0/fpm-alpine/entrypoint.sh
3.0/fpm/entrypoint.sh
5.0/apache/entrypoint.sh
5.0/fpm-alpine/entrypoint.sh
5.0/fpm/entrypoint.sh
README.md

In order to scale LimeSurvey horizontally we need the sessions to be at a central point. LS is able to store sessions in its database, this PR adds a variable to enable this setting.
I wanted to add this to a new config file named `session.php`, but I'm not sure if and how that would work. (I'm no PHP dev)
So, I had to refactor the creation of the config.php a bit... maybe there is a better way.
Fixes #75 
PS: Also the SHOW_SCRIPT_NAME variable was missing in LS 3.* - fixed now

Add variable for setting table session

---

nginx-certbot/entrypoint.sh

- added missing $ for variable
- removed ``"``` which lead to cert bot incorrrectly reading "-d example.com" as a whole as an argument, and throwing an error

Bug fixes for certbot-nginx config.

---

docker-compose.pgsql.yml

This makes more clear for those who want to use the LTS version of limesurvey, that some adaptations are needed. I had to spend a couple of hours to figure out that changes. Want to spare other people this time.

Include Hints to use in limesurvey 3.

---

3.0/apache/entrypoint.sh
3.0/fpm-alpine/entrypoint.sh
3.0/fpm/entrypoint.sh
5.0/apache/entrypoint.sh
5.0/fpm-alpine/entrypoint.sh
5.0/fpm/entrypoint.sh
README.md
docker-compose.yml

- Who are we to dictate a table prefix
- Makes it easier to migrate existing databases that don't have a prefix
Fixes #88

Update entrypoint to enable an empty table prefix

---

docker-compose.fpm.alpine.yml

Depending on how the containers start up, nginx fails if it can't find the limesurvey app:
lime-web_1    | 2021/11/23 17:06:34 [emerg] 1#1: host not found in upstream "limesurvey" in /etc/nginx/nginx.conf:33
lime-web_1    | nginx: [emerg] host not found in upstream "limesurvey" in /etc/nginx/nginx.conf:33
By adding a depends_on in lime-web, it will wait for the limesurvey app to be ready to accept connections.

Add depends_on for nginx so it waits until the limesurvey app is ready

---

examples/nginx.conf

With this config files in application/ are not directly accessable.
See #101

Extend example nginx.conf to include more protected paths

---

.github/workflows/build-latest-container-images.yaml
.github/workflows/build-lts-container-images.yaml

Previously, only the immutable tags would get generated (i.e.
`5.1.2-1234`), but not the rolling tags (`5-apache`), due to a
limitation of the docker metadata action.
Thus, now we use manual regex matching instead.
See the linked issue for details.
Fixes https://github.com/martialblog/docker-limesurvey/issues/105

Fix image tag generation

---

README.md
docker-compose.traefik.yml
examples/apache-example.conf

While the proxy is usually able to strip the prefix before routing to the Container, this won't work (for some reason). 
Users will have to pass a webserver Configuration with an Alias, as shown in this example. 
Fixes #106  
Fixes #42

Add a Traefik example with subpath

---

.github/workflows/build-latest-container-images.yaml

It shouldn't be used, but can be. Who are we to impede users from living on the edge?
Fixes #114

Enable :latest Tag for Apache Image

---

3.0/apache/Dockerfile
3.0/fpm-alpine/Dockerfile
3.0/fpm/Dockerfile
4.0/apache/Dockerfile
4.0/fpm-alpine/Dockerfile
4.0/fpm/Dockerfile
5.0/apache/Dockerfile
5.0/fpm-alpine/Dockerfile
5.0/fpm/Dockerfile

Allows building the images from LimeSurvey forks.
For example:
```bash
docker build \
--build-arg version=18158-delete_question-findAllByAttributes \
--build-arg sha256_checksum=0f5d94dd66eec828b10c188bd2e99cba4dcad0727f8345b7844e47be0d7a71ec \
--build-arg repository=edgarrmondragon/LimeSurvey \
-t ls-test \
'https://github.com/edgarrmondragon/docker-limesurvey#feat-repository-arg:5.0'
```

feat: Add a 'repository' build argument

---

3.0/apache/Dockerfile
3.0/fpm-alpine/Dockerfile
3.0/fpm/Dockerfile
5.0/apache/Dockerfile
5.0/fpm-alpine/Dockerfile
5.0/fpm/Dockerfile

Benefits:
- Re-builds are faster since they use the cache of the first `RUN` layer
- Earlier layers can be eventually templated (as in https://github.com/docker-library/postgres/blob/master/apply-templates.sh)

Move `ARG` instructions right before where they are used

---

.github/workflows/build-latest-container-images.yaml
.github/workflows/build-lts-container-images.yaml
.github/workflows/lint-dockerfiles.yaml
.github/workflows/test-arm-container-images.yaml
.github/workflows/test-latest-container-images.yaml
.github/workflows/test-lts-container-images.yaml
6.0/apache/Dockerfile
6.0/apache/entrypoint.sh
6.0/apache/vhosts-access-log.conf
6.0/fpm-alpine/Dockerfile
6.0/fpm-alpine/entrypoint.sh
6.0/fpm/Dockerfile
6.0/fpm/entrypoint.sh
CONTRIBUTING.md
Makefile
README.md
docker-compose.apache.yml
docker-compose.fpm-certbot.yml
docker-compose.fpm.alpine.yml
docker-compose.fpm.yml
docker-compose.pgsql.yml
docker-compose.traefik.domain.yml
docker-compose.traefik.yml
docker-compose.yml
tests/apache-tests.yaml
upgrade.sh

LimeSurvey announced the Release 6.0. With that 5.0 becomes the new LTS and 3.0 is deprecated (support ends Q2 2023).
Updated the repo accordingly.
PR includes:
- Update GitHub Action versions
- Add ARM build in GitHub Actions
- Update Repository for new 6.0 Release

Update Repository for new 6.0 Release

---

3.0/fpm-alpine/Dockerfile
5.0/fpm-alpine/Dockerfile
6.0/fpm-alpine/Dockerfile

This reduces the image size by ~50%.
There is a similar approach for the Debian base if you're interested.

Drop build dependencies from Alpine variant

---

3.0/apache/Dockerfile
3.0/fpm/Dockerfile
5.0/apache/Dockerfile
5.0/fpm/Dockerfile
6.0/apache/Dockerfile
6.0/fpm/Dockerfile

Some additional clean-ups:
- remove redundant `DEBIAN_FRONTEND=noninteractive`
- fix LDAP library detection
- auto-detect available cores for parallel builds

Drop build dependencies from Debian variant

---

docker-compose.example.yml

In using this docker-compose found that because the db-data volume was different to that in the postgres:10-alpine dockerfile the system did not persist data between down and up of docker-compose.   Added /data to volume path and now all works.

The volume path for db-data was wrong.   needed data sub-folder.   Without that wasn't persisting the db on stop of container.

---

6.0/apache/Dockerfile
6.0/fpm/Dockerfile

- Due to the PHP libs being at /lib in newer Image versions the apt-mark manual wouldn't catch them and remove important libraries. This extends the marking of required packages.
Relates to #177

Improve removal of dev packages

---

6.0/apache/Dockerfile
6.0/fpm-alpine/Dockerfile
6.0/fpm/Dockerfile

PHP 8.2.0 was released 08 Dec 2022 (see https://www.php.net/releases/index.php).
This repo uses Renovate and that may already bump these automatically, so let me know if you're explicitly avoiding bumping the version.
EDIT: tests are failing, so maybe that's enough reason to punt the update 😅.

Bump PHP to 8.1 in 6.x images

---

nginx-certbot/Dockerfile

python-certbot-nginx package has been replaced with python3-certbot-nginx package.

Update Dockerfile in nginx-certbot: python-certbot-nginx => python3-certbot-nginx

---

docker-compose.pgsql.yml
docker-compose.yml

Tested newest postgres version without issues, would be great if somebody tests mariadb as well

Update compose templates for mysql and postgres

---

README.md
docker-compose.example.yml
examples/apache-example.conf

This PR changes the example persistent data config to keep also other directories, like `theme`, `plugins` etc. in the volume. The whole `upload` directory is intended for persistent data and current example config causes e.g. lose of theme modifications on the container upgrade.
In addition, the "Known issues" section discusses the topic as well as another issue with the Apache, which tries to use its own port when redirecting to canonical URLs. When put behind another proxy listening on different ports, it produces URLs not accessible by the client.
Close #196

Keep all upload data persistent and advice on redirections issues
