- .gitignore
- .travis.yml
- tests/image_tests.yaml
- tests/run.sh
> Add container-structore tests

- .travis.yml
- docker-compose.fpm.alpine.yml
- fpm-alpine/Dockerfile
- fpm-alpine/entrypoint.sh
Add a smaller Image based on fpm-alpine (currently 384MB)
Fixes #8
> Add fpm-alpine Dockerfile

- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
Its two spaces... TWO SPACES!
https://github.com/gliderlabs/docker-alpine/issues/174#issuecomment-222951567
> Fix sha256sum check

- README.md
- apache/Dockerfile
- docker-compose.fpm.alpine.yml
- docker-compose.fpm.yml
- docker-compose.pgsql.yml
- docker-compose.yml
- fpm-alpine/Dockerfile
- fpm/Dockerfile
The gd wasn't configured properly.
Also updated the docker-compose files to ensure the upload folder is mounted correctly.
Fixes: https://github.com/martialblog/docker-limesurvey/issues/20
> Fix gd library configuration and update example docker-compose files

- 3.0/apache/Dockerfile
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm/Dockerfile
- 4.0/apache/Dockerfile
- 4.0/fpm-alpine/Dockerfile
- 4.0/fpm/Dockerfile
- More secure than ADD
- Makes better use of cache
>  Change download of Limesurvey to curl

- 3.0/apache/Dockerfile
- 3.0/apache/entrypoint.sh
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm-alpine/entrypoint.sh
- 3.0/fpm/Dockerfile
- 3.0/fpm/entrypoint.sh
- 4.0/apache/Dockerfile
- 4.0/apache/entrypoint.sh
- 4.0/fpm-alpine/Dockerfile
- 4.0/fpm-alpine/entrypoint.sh
- 4.0/fpm/Dockerfile
- 4.0/fpm/entrypoint.sh
- README.md
Rewrote the entrypoint to be a bit more flexible. 
- Debugging can be adjusted
- Data encryption keys can now be provided (plus a warning if you use non-persistent keys) - Fixes #33 
- Should be easier to add new variables in the future
> Refactor entrypoint

- 3.0/apache/Dockerfile
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm/Dockerfile
- 4.0/apache/Dockerfile
- 4.0/fpm-alpine/Dockerfile
- 4.0/fpm/Dockerfile
Fixes https://github.com/martialblog/docker-limesurvey/issues/51
> Fix gd installation and add tidy/sodium lib

- 3.0/apache/Dockerfile
- 4.0/apache/Dockerfile
- makefile
In preparation to #60 , this change allows to run the containers as www-data. I will add this to the autobuild and provide tags for the images.
Thanks to @eidottermihi 's #59 , this was a very minor change. :medal_sports:
> Add configuration to run apache containers as www-data user

- .github/workflows/build-latest-container-images.yaml
* YAML indentation
* Correct image labels
> Minor workflow fixes

- 3.0/apache/entrypoint.sh
- 3.0/fpm-alpine/entrypoint.sh
- 3.0/fpm/entrypoint.sh
- 4.0/apache/entrypoint.sh
- 4.0/fpm-alpine/entrypoint.sh
- 4.0/fpm/entrypoint.sh
- 5.0/apache/entrypoint.sh
- 5.0/fpm-alpine/entrypoint.sh
- 5.0/fpm/entrypoint.sh
- nginx-certbot/entrypoint.sh
- upgrade.sh
This adds suggestions by [shellcheck](https://www.shellcheck.net/) to the entry point scripts and a few minor tweaks to use `sh` builtins instead of command
> Add suggestions from shellcheck

- .github/workflows/test-latest-container-images.yaml
- .github/workflows/test-lts-container-images.yaml
Since we are not in charge of the app
> Update Trivy config to only scan type 'os'

- 3.0/apache/Dockerfile
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm/Dockerfile
- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
- tests/apache-tests.yaml
- tests/fpm-alpine-tests.yaml
- so that it's not served by the webserver
See #101
> Move entrypoint to /usr/local/bin

- 3.0/apache/Dockerfile
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm/Dockerfile
- 4.0/apache/Dockerfile
- 4.0/fpm-alpine/Dockerfile
- 4.0/fpm/Dockerfile
- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
PHP 8.1 deprecation notices and other stuff
> Limesurvey not compatible with 8.1 docker image

- docker-compose.pgsql.yml
Fixes https://github.com/martialblog/docker-limesurvey/issues/112
> Correct path to data volume of Postgres deployment

- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
Released April 11th: https://github.com/LimeSurvey/LimeSurvey/releases/tag/5.3.8%2B220404
> Upgrade to 5.3.8+220404

- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
Released May 9th: https://github.com/LimeSurvey/LimeSurvey/releases/tag/5.3.12%2B220502
> Upgrade to 5.3.12+220502

- 3.0/apache/Dockerfile
- 3.0/fpm-alpine/Dockerfile
- 3.0/fpm/Dockerfile
- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
- docker-compose.example.yml
- docker-compose.fpm-certbot.yml
- docker-compose.fpm.alpine.yml
- docker-compose.fpm.yml
- docker-compose.pgsql.yml
- docker-compose.traefik.yml
- docker-compose.yml
Makes it simpler to work with different Container Runtimes
> Change Container Image Names to FQDN

- README.md
- docker-compose.apache.yml
- docker-compose.traefik.domain.yml
- examples/apache-httpd.conf
- examples/apache-reverse-proxy.conf
These issues are related:
- https://github.com/martialblog/docker-limesurvey/issues/49
- https://github.com/martialblog/docker-limesurvey/issues/106
- https://github.com/martialblog/docker-limesurvey/issues/127
- https://github.com/martialblog/docker-limesurvey/issues/132
Special Thanks to @jimartinezabadias who found this solution.
> Add docker-compose example with Apache reverse-proxy

- .github/workflows/build-lts-container-images.yaml
> Fix LTS platform build

- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
- 6.0/apache/Dockerfile
- 6.0/fpm-alpine/Dockerfile
- 6.0/fpm/Dockerfile
> Add OS libraries for ldaps

- 5.0/apache/entrypoint.sh
- 5.0/fpm-alpine/entrypoint.sh
- 5.0/fpm/entrypoint.sh
- 6.0/apache/entrypoint.sh
- 6.0/fpm-alpine/entrypoint.sh
- 6.0/fpm/entrypoint.sh
- README.md
> Add support for secrets in files

- README.md
- docker-compose.apache.yml
- docker-compose.example.yml
- docker-compose.fpm-certbot.yml
- docker-compose.fpm.alpine.yml
- docker-compose.fpm.yml
- docker-compose.pgsql.yml
- docker-compose.traefik.domain.yml
- docker-compose.traefik.yml
- docker-compose.yml
- To discourage production use without changing the passwords.
> Remove default passwords in all example files

- 5.0/apache/entrypoint.sh
- 5.0/fpm-alpine/entrypoint.sh
- 5.0/fpm/entrypoint.sh
- 6.0/apache/entrypoint.sh
- 6.0/fpm-alpine/entrypoint.sh
- 6.0/fpm/entrypoint.sh
… and $ENCRYPT_KEYPAIR is missing
This fixes #173 
best regards
> Now security.php is created properly if $ENCRYPT_SECRET_BOX_KEY is set

- 5.0/apache/Dockerfile
- 5.0/fpm-alpine/Dockerfile
- 5.0/fpm/Dockerfile
https://github.com/LimeSurvey/LimeSurvey/releases/tag/5.6.68%2B240625
> Upgrading to LTS Version 5.6.68+240625

- .github/workflows/update-latest-tag.yaml
Hey @martialblog!
I've wanted to offer this contribution for a really long time and I finally found some spare time to do it.
There's an example PR in https://github.com/edgarrmondragon/docker-limesurvey/pull/2.
Let me know what you think 🙂
> Automate updates to the latest 6.x tag

- 6.0/apache/Dockerfile
- 6.0/fpm-alpine/Dockerfile
- 6.0/fpm/Dockerfile
> Bump LS6 PHP to 8.3
